// solid/src/Gallery.tsx
import { type Component, For } from 'solid-js';
import Card from './Card';

interface CardProps {
  id: string;
  title: string;
  url: string;
}

interface GalleryProps {
  cards: CardProps[];
}

const Gallery: Component<GalleryProps> = (props) => {
  return (
    <div id="gallery" class="gallery grid grid-cols-1 gap-4 lg:grid-cols-2 lg:gap-8 px-12">
      <For each={props.cards}>{(cardProps) => <Card {...cardProps} />}</For>
    </div>
  );
};

export default Gallery;

// react/src/Gallery.tsx
import React from 'react';
import Card from './Card';

interface CardProps {
  id: string;
  title: string;
  url: string;
}

interface GalleryProps {
  cards: CardProps[];
}

const Gallery: React.FC<GalleryProps> = ({ cards }) => {
  return (
    <div id="gallery" className="gallery grid grid-cols-1 gap-4 lg:grid-cols-2 lg:gap-8 px-12">
      {cards.map((cardProps) => (
        <Card key={cardProps.id} {...cardProps} />
      ))}
    </div>
  );
};

export default Gallery;
